CREATE TABLE IF NOT EXISTS schema_migrations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  migration_name TEXT NOT NULL UNIQUE,
  checksum TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
